patch_id: "19.30"
description: "Oracle 19c RU 19.30 + OJVM + OPatch"

opatch_zip: "p6880880_190000_Linux-x86-64.zip"
gi_zip: "p_gi_19.30_linux_x86-64.zip"
dbru_zip: "p_dbru_19.30_linux_x86-64.zip"
ojvm_zip: "p_ojvm_19.30_linux_x86-64.zip"

opatch_dir: "OPatch"
gi_dir: "38629535"
dbru_dir: "38632161"
ojvm_dir: "38523609"

pre_datapatch_sql: "pre_datapatch.sql"
